---
name: release binaries

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v2

      - name: create binary files
        run: make binary

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: $
